apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}
  labels:
    app: {{ include "myapp.name" . }}
  annotations:
    prometheus.io/scrape: "{{ .Values.metrics.enabled }}"
    prometheus.io/path: "{{ .Values.metrics.path }}"
    prometheus.io/port: "{{ .Values.metrics.port }}"
spec:
  type: ClusterIP
  selector:
    app: {{ include "myapp.name" . }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.service.port }}
